### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Chendx73** [ZzMeei/AdaptiveGCL#1]
作者你好！请问能分享一下数据集预处理代码吗？
谢谢！！

**Comment by yangqin-jiang** [comment]
您好，

感谢您对我们工作的关注。

Yelp数据集我们follow了其他工作的数据，剩下两个数据集是从网上获得的公开数据集，其中LastFM没有做任何处理，只是转化成了稀疏矩阵的形式，BeerAdvocate进行了n-core的过滤，之后再转化成了稀疏矩阵的形式。如果您需要将自己的数据集处理成我们工作代码能够使用的格式，只需要将用户-物品交互矩阵转化为numpy稀疏矩阵即可。

我希望这些能够解决您的问题。

**Comment by Chendx73** [comment]
感谢
